# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # DANGER: this UUID (the old Games partition) is only valid as root AFTER
  # completing the live-USB migration in ./ROOT_GAMES_MERGE.md. Until then,
  # do not `nixos-rebuild switch`/`boot` this config on the machine as it
  # currently exists (root still on the old, since-deleted partition) — the
  # next boot would fail to find root, with no fallback generation to
  # recover to (configurationLimit = 1). This UUID only becomes correct
  # once you're chrooted into the migrated system in Phase 8 of that doc.
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c8a9b8f2-74f1-42b9-88b0-86853c3c6544";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F657-B6E4";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
